version: '3'

vars:
  BINARY_NAME: pop3d
  BUILD_DIR: ./bin

tasks:
  default:
    desc: Run all checks (build, lint, vulncheck, test)
    cmds:
      - task: all

  build:
    desc: Build the Go binary
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} ./cmd/pop3d
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  vulncheck:
    desc: Run govulncheck for security vulnerabilities
    cmds:
      - govulncheck ./...

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  all:
    desc: Run all checks (build, lint, vulncheck, test)
    cmds:
      - task: build
      - task: lint
      - task: vulncheck
      - task: test

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html

  install:deps:
    desc: Install development dependencies
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  hooks:install:
    desc: Configure git to use the project hooks directory
    cmds:
      - git config core.hooksPath .githooks
      - echo "Git hooks installed from .githooks directory"

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t infodancer-pop3d:latest .

  docker:run:
    desc: Run pop3d container with maildir storage
    vars:
      CONFIG_PATH:
        sh: mktemp -d -t pop3d-config-XXXXXX
      STORAGE_PATH:
        sh: mktemp -d -t pop3d-storage-XXXXXX
    cmds:
      - 'echo "Config: {{.CONFIG_PATH}}, Storage: {{.STORAGE_PATH}}"'
      - |
        docker run -p 1110:110 -p 1995:995 \
          -v {{.CONFIG_PATH}}:/etc/infodancer:ro \
          -v {{.STORAGE_PATH}}:/var/infodancer \
          -e POP3D_HOSTNAME=localhost \
          -e POP3D_MAILDIR=/var/infodancer/domains \
          -e POP3D_LOG_LEVEL=debug \
          infodancer-pop3d:latest
